# PROMPT:
# Create pytest fixtures for testing a FastAPI + SQLAlchemy SQLite API.
# The tests should use an isolated test database and FastAPI TestClient.
#
# HUMAN CHANGES:
# Adapted imports to the current repository structure where api/main.py imports
# database.py and models.py as local modules. Added sys.path handling so tests
# can run from the project root on Windows and Linux.

import os
import sys
import uuid
from pathlib import Path
from datetime import datetime, timezone

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine


PROJECT_ROOT = Path(__file__).resolve().parents[1]
API_DIR = PROJECT_ROOT / "api"

# main.py imports database.py as "database", so api/ must be on sys.path.
if str(API_DIR) not in sys.path:
    sys.path.insert(0, str(API_DIR))

import database  # noqa: E402


TEST_DATABASE_URL = "sqlite:///./test_store_intelligence.db"

test_engine = create_engine(
    TEST_DATABASE_URL,
    connect_args={"check_same_thread": False},
)

# Rebind the existing SessionLocal to the test database.
database.engine = test_engine
database.SessionLocal.configure(bind=test_engine)

from main import app  # noqa: E402


@pytest.fixture(autouse=True)
def reset_test_database():
    """
    Reset database tables before every test.

    This keeps tests deterministic and avoids dependence on runtime data
    generated by the CV pipeline.
    """

    database.Base.metadata.drop_all(bind=test_engine)
    database.Base.metadata.create_all(bind=test_engine)

    yield

    database.Base.metadata.drop_all(bind=test_engine)

    try:
        os.remove("test_store_intelligence.db")
    except FileNotFoundError:
        pass


@pytest.fixture
def client():
    with TestClient(app) as test_client:
        yield test_client


@pytest.fixture
def sample_event():
    def _make_event(
        event_id=None,
        event_type="ENTRY",
        visitor_id="VIS_TEST_1",
        zone_id=None,
        dwell_ms=None,
        is_staff=False,
        confidence=0.95,
        session_seq=1,
        queue_depth=None,
        sku_zone=None,
        timestamp=None,
    ):
        return {
            "event_id": event_id or str(uuid.uuid4()),
            "store_id": "ST1008",
            "camera_id": "CAM_TEST",
            "visitor_id": visitor_id,
            "timestamp": timestamp or datetime.now(timezone.utc).isoformat(),
            "event_type": event_type,
            "zone_id": zone_id,
            "dwell_ms": dwell_ms,
            "is_staff": is_staff,
            "confidence": confidence,
            "metadata": {
                "queue_depth": queue_depth,
                "sku_zone": sku_zone,
                "session_seq": session_seq,
            },
        }

    return _make_event