from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional, List
from datetime import datetime
import uuid


# Define the event types supported by the challenge/event pipeline.
class EventType(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    ZONE_ENTER = "ZONE_ENTER"
    ZONE_EXIT = "ZONE_EXIT"
    ZONE_DWELL = "ZONE_DWELL"
    BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
    BILLING_QUEUE_EXIT = "BILLING_QUEUE_EXIT"

    # Added for schema compatibility with the challenge.
    # These are not fully generated by the current CV pipeline yet,
    # but the API can now validate them when implemented later.
    REENTRY = "REENTRY"
    BILLING_QUEUE_ABANDON = "BILLING_QUEUE_ABANDON"


class EventMetadata(BaseModel):
    """
    Optional nested metadata object required by the challenge schema.

    queue_depth:
        Current queue depth for BILLING_QUEUE_JOIN / BILLING_QUEUE_EXIT events.

    sku_zone:
        Business-friendly zone label. For now this mirrors zone_id.

    session_seq:
        Local ordinal position of this event in the visitor's session.
        In the current implementation this is local to the camera/state machine.
    """

    queue_depth: Optional[int] = Field(default=None, ge=0)
    sku_zone: Optional[str] = None
    session_seq: Optional[int] = Field(default=None, ge=1)


class Event(BaseModel):
    """
    Core event schema accepted by POST /events/ingest.

    This is Event Schema v1.2:
    - Keeps the previously implemented flattened fields.
    - Adds challenge-compatible nested metadata.
    - Remains backward-compatible because metadata has a default value.
    """

    event_id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        description="Unique identifier for the event",
    )
    store_id: str = Field(..., description="Unique store identifier")
    camera_id: str = Field(..., description="Camera identifier generating the event")
    visitor_id: str = Field(..., description="Persistent track ID assigned to a person")
    timestamp: datetime = Field(..., description="ISO-8601 UTC timestamp")
    event_type: EventType = Field(..., description="Type of the event from the catalogue")
    zone_id: Optional[str] = Field(default=None, description="Zone identifier for zone events")

    dwell_ms: Optional[int] = Field(
        default=None,
        ge=0,
        description="Dwell time in milliseconds",
    )
    is_staff: bool = Field(
        default=False,
        description="True if the person is identified as staff",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Detection/tracking confidence score",
    )

    metadata: EventMetadata = Field(
        default_factory=EventMetadata,
        description="Challenge-compatible event metadata",
    )


class EventIngestRequest(BaseModel):
    """
    Batch ingestion request.

    Challenge limit: up to 500 events per request.
    """

    events: List[Event] = Field(
        ...,
        max_length=500,
        description="Batch of events, maximum 500",
    )


class EventIngestResponse(BaseModel):
    status: str
    processed_count: int
    errors: Optional[List[dict]] = None